import './globals.css'
import {Inter, Roboto} from 'next/font/google'
import {Header} from "@/components/Header/Header";
import {Footer} from "@/components/Footer/Footer";
import classNames from "classnames";
import {StoreProvider} from "@/redux/storeProvider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const roboto = Roboto({
    weight: ['400', '700', '100', '300', '500', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
})
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={classNames(inter.className, roboto.className)}>
                <StoreProvider>
                    <Header/>
                    <main>
                        {children}
                    </main>
                    <Footer/>
                </StoreProvider>
            </body>
        </html>
    )
}
